In [1]:
import pandas as pd
import numpy as np
import csv
from collections import defaultdict

In [2]:
df = pd.read_csv("deliveries.csv")

In [3]:
'''
df1 and df2 can be combined to see the 4s and 6s together if needed. 
you just need to copy the total_runs column from df2 to df1
'''
#has all the 4s for a team in each over all the seasons
df1 = pd.DataFrame(df[df.total_runs == 4].groupby(["batting_team","over"]).count()["total_runs"])
df1.to_csv("perteam4s.csv")
#has all the 6s for a team in each over all the seasons
df2 = pd.DataFrame(df[df.total_runs == 6].groupby(["batting_team","over"]).count()["total_runs"])
df2.to_csv("perteam6s.csv")
#has all the 4s per over for all the teams combined
df4 = pd.DataFrame(df[df.total_runs == 4].groupby(["over"]).count()["total_runs"])
df4.to_csv("perover4s.csv")
#has all the 6s for all the teams combined
df5 = pd.DataFrame(df[df.total_runs == 6].groupby(["over"]).count()["total_runs"])
df5.to_csv("perover6s.csv")

'''
Extas provided by the bowling team
'''
#extras given by the bowling team per over
df6 = pd.DataFrame(df[df.extra_runs > 0].groupby(["bowling_team","batting_team","over"]).count()["total_runs"])
df6.to_csv("perteamextrasbybowlingteam.csv")
#extras given by the bowling team over all
df3 = pd.DataFrame(df[df.extra_runs > 0].groupby(["bowling_team","batting_team"]).count()["total_runs"])
df3.to_csv("perteamextrasbybowlingteam_agg.csv")

In [4]:
dfm = pd.DataFrame(pd.read_csv("matches.csv"))
dfm.head(5)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [5]:
'''
finding the competing teams, who won the toss and who won the game
'''
for i in range(2008,2018):
    query = "season==" +str(i)
    filename = "winners"+ str(i) + "permatch.csv"
    dfm1 = pd.DataFrame(dfm.query(query)[["team1","team2","toss_winner","toss_decision","winner"]])
    dfm1.to_csv(filename)

In [6]:
'''
finding the count of matches for which a player got player of the match
'''
dfm2 = dfm.groupby("player_of_match").count()[["id"]].sort_values("id", ascending = False)
dfm2.to_csv("palyerofthematch.csv")

In [6]:
'''
Runs scored by a batsman

'''
player = defaultdict(int)
player_runs = defaultdict(lambda: defaultdict(int))

for i,row in df.iterrows():
    player[row["batsman"]] += (row["total_runs"]-row["extra_runs"])
    player_runs[row["batsman"]][row["total_runs"]-row["extra_runs"]]+=1

In [7]:
player_runs

defaultdict(<function __main__.<lambda>>,
            {'A Ashish Reddy': defaultdict(int,
                         {0: 61, 1: 83, 2: 20, 3: 1, 4: 16, 6: 15}),
             'A Chandila': defaultdict(int, {0: 3, 1: 4}),
             'A Chopra': defaultdict(int, {0: 45, 1: 21, 2: 2, 4: 7}),
             'A Choudhary': defaultdict(int, {0: 4, 1: 13, 2: 1, 4: 1, 6: 1}),
             'A Flintoff': defaultdict(int,
                         {0: 24, 1: 23, 2: 2, 3: 1, 4: 5, 6: 2}),
             'A Kumble': defaultdict(int, {0: 24, 1: 21, 2: 1, 4: 3}),
             'A Mishra': defaultdict(int,
                         {0: 168, 1: 162, 2: 20, 4: 27, 6: 5}),
             'A Mithun': defaultdict(int, {0: 11, 1: 8, 2: 2, 4: 4, 6: 1}),
             'A Mukund': defaultdict(int, {0: 9, 1: 11, 2: 2, 4: 1}),
             'A Nehra': defaultdict(int, {0: 37, 1: 21, 2: 1, 4: 3, 6: 1}),
             'A Singh': defaultdict(int, {0: 8, 1: 2}),
             'A Symonds': defaultdict(int,
                         {0: 308, 1: 288, 2: 66, 3: 4, 4: 74, 6: 41}),
             'A Uniyal': defaultdict(int, {0: 3, 1: 4}),
             'A Zampa': defaultdict(int, {0: 6, 1: 1, 4: 1}),
             'AA Bilakhia': defaultdict(int, {0: 43, 1: 31, 2: 9, 4: 5}),
             'AA Chavan': defaultdict(int, {0: 5, 1: 4, 4: 2}),
             'AA Jhunjhunwala': defaultdict(int,
                         {0: 98, 1: 82, 2: 13, 3: 1, 4: 19, 6: 5}),
             'AA Noffke': defaultdict(int, {0: 6, 1: 5, 4: 1}),
             'AB Agarkar': defaultdict(int,
                         {0: 60, 1: 67, 2: 15, 4: 13, 6: 5}),
             'AB Barath': defaultdict(int, {0: 22, 1: 14, 2: 1, 4: 5, 6: 1}),
             'AB Dinda': defaultdict(int, {0: 31, 1: 16, 2: 1, 4: 2}),
             'AB McDonald': defaultdict(int,
                         {0: 38, 1: 42, 2: 9, 3: 1, 4: 9, 6: 4}),
             'AB de Villiers': defaultdict(int,
                         {0: 778, 1: 980, 2: 187, 3: 12, 4: 287, 6: 158}),
             'AC Blizzard': defaultdict(int,
                         {0: 48, 1: 17, 2: 2, 3: 1, 4: 21, 6: 2}),
             'AC Gilchrist': defaultdict(int,
                         {0: 737, 1: 417, 2: 66, 3: 4, 4: 239, 6: 92}),
             'AC Thomas': defaultdict(int, {0: 8, 1: 8, 2: 1, 4: 1, 6: 1}),
             'AC Voges': defaultdict(int,
                         {0: 44, 1: 61, 2: 18, 3: 2, 4: 15, 6: 3}),
             'AD Mascarenhas': defaultdict(int,
                         {0: 29, 1: 35, 2: 9, 4: 5, 6: 1}),
             'AD Mathews': defaultdict(int,
                         {0: 207, 1: 267, 2: 49, 3: 3, 4: 44, 6: 29}),
             'AD Nath': defaultdict(int, {0: 14, 1: 10, 2: 3, 4: 1}),
             'AD Russell': defaultdict(int,
                         {0: 128, 1: 114, 2: 23, 4: 48, 6: 37}),
             'AF Milne': defaultdict(int, {0: 6, 1: 5, 2: 1}),
             'AG Murtaza': defaultdict(int, {0: 7, 1: 6, 4: 1}),
             'AG Paunikar': defaultdict(int, {0: 41, 1: 9, 2: 2, 4: 9}),
             'AJ Finch': defaultdict(int,
                         {0: 554, 1: 407, 2: 77, 3: 3, 4: 170, 6: 59}),
             'AJ Tye': defaultdict(int, {0: 8, 1: 11, 2: 4, 4: 4, 6: 3}),
             'AL Menaria': defaultdict(int,
                         {0: 152, 1: 149, 2: 24, 4: 24, 6: 18}),
             'AM Nayar': defaultdict(int,
                         {0: 234, 1: 230, 2: 47, 3: 1, 4: 55, 5: 1, 6: 20}),
             'AM Rahane': defaultdict(int,
                         {0: 1001, 1: 1039, 2: 168, 3: 14, 4: 320, 6: 60}),
             'AN Ahmed': defaultdict(int, {0: 11, 1: 8, 2: 3, 4: 4, 6: 1}),
             'AN Ghosh': defaultdict(int, {0: 5, 1: 1, 2: 1, 4: 1}),
             'AP Dole': defaultdict(int, {0: 7, 1: 8, 2: 4, 4: 3, 6: 1}),
             'AP Majumdar': defaultdict(int, {0: 28, 1: 33, 2: 7, 4: 7, 6: 2}),
             'AP Tare': defaultdict(int,
                         {0: 142, 1: 72, 2: 19, 3: 1, 4: 40, 6: 11}),
             'AR Bawne': defaultdict(int, {0: 4, 1: 6, 2: 1, 4: 1}),
             'AR Patel': defaultdict(int,
                         {0: 169, 1: 224, 2: 39, 4: 34, 6: 28}),
             'AS Rajpoot': defaultdict(int, {0: 11, 2: 1, 4: 1}),
             'AS Raut': defaultdict(int,
                         {0: 67, 1: 73, 2: 9, 3: 3, 4: 13, 6: 7}),
             'AS Yadav': defaultdict(int, {0: 18, 1: 13, 2: 2, 4: 5, 6: 2}),
             'AT Rayudu': defaultdict(int,
                         {0: 693, 1: 853, 2: 133, 3: 1, 4: 205, 6: 79}),
             'AUK Pathan': defaultdict(int, {0: 14, 1: 3, 2: 2, 4: 5, 6: 2}),
             'Abdur Razzak': defaultdict(int, {0: 2}),
             'Anirudh Singh': defaultdict(int,
                         {0: 34, 1: 23, 2: 5, 4: 6, 6: 1}),
             'Ankit Sharma': defaultdict(int,
                         {0: 29, 1: 23, 2: 6, 4: 7, 6: 4}),
             'Ankit Soni': defaultdict(int, {0: 7, 1: 1, 6: 1}),
             'Anureet Singh': defaultdict(int, {0: 21, 1: 19, 4: 2, 6: 1}),
             'Azhar Mahmood': defaultdict(int,
                         {0: 124, 1: 116, 2: 19, 4: 39, 6: 13}),
             'B Akhil': defaultdict(int, {0: 26, 1: 16, 2: 5, 4: 5, 6: 5}),
             'B Chipli': defaultdict(int,
                         {0: 110, 1: 100, 2: 7, 3: 4, 4: 28, 6: 7}),
             'B Kumar': defaultdict(int, {0: 76, 1: 52, 2: 14, 4: 15, 6: 3}),
             'B Laughlin': defaultdict(int, {0: 5, 1: 4}),
             'B Lee': defaultdict(int, {0: 46, 1: 36, 2: 4, 4: 8, 6: 8}),
             'B Sumanth': defaultdict(int, {0: 15, 1: 17, 2: 3, 4: 3}),
             'BA Bhatt': defaultdict(int, {0: 6, 6: 1}),
             'BA Stokes': defaultdict(int,
                         {0: 70, 1: 102, 2: 18, 4: 22, 6: 15}),
             'BAW Mendis': defaultdict(int, {0: 3, 1: 3}),
             'BB McCullum': defaultdict(int,
                         {0: 985, 1: 690, 2: 102, 3: 3, 4: 277, 6: 124}),
             'BB Samantray': defaultdict(int,
                         {0: 48, 1: 45, 2: 8, 4: 13, 6: 2}),
             'BB Sran': defaultdict(int, {1: 4}),
             'BCJ Cutting': defaultdict(int,
                         {0: 27, 1: 20, 2: 4, 4: 9, 6: 10}),
             'BE Hendricks': defaultdict(int, {0: 2, 1: 1}),
             'BJ Haddin': defaultdict(int, {0: 5, 1: 2, 2: 1, 4: 2, 6: 1}),
             'BJ Hodge': defaultdict(int,
                         {0: 439, 1: 452, 2: 89, 3: 8, 4: 122, 6: 43}),
             'BJ Rohrer': defaultdict(int,
                         {0: 57, 1: 48, 2: 14, 3: 1, 4: 21, 6: 5}),
             'BMAJ Mendis': defaultdict(int, {0: 8, 1: 15, 2: 4}),
             'BR Dunk': defaultdict(int, {0: 20, 1: 6, 2: 3, 4: 7}),
             'Basil Thampi': defaultdict(int,
                         {0: 13, 1: 12, 2: 3, 4: 1, 6: 1}),
             'Bipul Sharma': defaultdict(int,
                         {0: 34, 1: 51, 2: 19, 4: 11, 6: 9}),
             'C Madan': defaultdict(int, {0: 15, 1: 3, 4: 3}),
             'C Munro': defaultdict(int, {0: 13, 1: 12, 2: 3, 4: 3}),
             'C Nanda': defaultdict(int, {0: 1}),
             'C de Grandhomme': defaultdict(int,
                         {0: 31, 1: 40, 2: 5, 4: 10, 6: 6}),
             'CA Ingram': defaultdict(int, {0: 12, 1: 11, 2: 1, 4: 2}),
             'CA Lynn': defaultdict(int, {0: 103, 1: 84, 2: 19, 4: 31, 6: 23}),
             'CA Pujara': defaultdict(int,
                         {0: 200, 1: 133, 2: 15, 3: 1, 4: 50, 6: 4}),
             'CH Gayle': defaultdict(int,
                         {0: 1178, 1: 718, 2: 70, 3: 3, 4: 297, 6: 266}),
             'CH Morris': defaultdict(int,
                         {0: 78, 1: 113, 2: 28, 4: 33, 6: 23}),
             'CJ Anderson': defaultdict(int,
                         {0: 190, 1: 128, 2: 25, 3: 1, 4: 40, 6: 30}),
             'CJ Ferguson': defaultdict(int, {0: 58, 1: 42, 2: 10, 4: 9}),
             'CJ Jordan': defaultdict(int, {0: 3, 1: 1, 2: 1}),
             'CJ McKay': defaultdict(int, {0: 8, 1: 6, 2: 1}),
             'CK Kapugedera': defaultdict(int, {0: 10, 1: 12, 2: 2}),
             'CK Langeveldt': defaultdict(int, {0: 6, 1: 2, 6: 1}),
             'CL White': defaultdict(int,
                         {0: 274, 1: 335, 2: 49, 3: 2, 4: 76, 6: 38}),
             'CM Gautam': defaultdict(int,
                         {0: 84, 1: 40, 2: 8, 3: 3, 4: 17, 6: 6}),
             'CR Brathwaite': defaultdict(int,
                         {0: 27, 1: 11, 2: 2, 4: 8, 6: 8}),
             'CR Woakes': defaultdict(int, {0: 21, 1: 18, 2: 3, 4: 4, 6: 1}),
             'CRD Fernando': defaultdict(int, {1: 2, 2: 1}),
             'D Kalyankrishna': defaultdict(int, {0: 5, 1: 3}),
             'D Salunkhe': defaultdict(int, {0: 8, 1: 9, 2: 2, 4: 5}),
             'D Wiese': defaultdict(int, {0: 29, 1: 43, 2: 6, 4: 12, 6: 4}),
             'D du Preez': defaultdict(int, {0: 5, 1: 6, 2: 2}),
             'DA Miller': defaultdict(int,
                         {0: 382, 1: 464, 2: 106, 3: 1, 4: 104, 6: 78}),
             'DA Warner': defaultdict(int,
                         {0: 1124, 1: 997, 2: 207, 3: 13, 4: 401, 6: 160}),
             'DAJ Bracewell': defaultdict(int, {0: 1, 1: 6, 2: 1, 4: 1}),
             'DB Das': defaultdict(int, {0: 124, 1: 92, 2: 12, 4: 23, 6: 16}),
             'DB Ravi Teja': defaultdict(int,
                         {0: 124, 1: 136, 2: 18, 3: 3, 4: 35, 6: 9}),
             'DE Bollinger': defaultdict(int, {0: 11, 1: 9, 2: 1, 4: 1, 6: 1}),
             'DH Yagnik': defaultdict(int, {0: 62, 1: 44, 2: 11, 4: 23, 6: 2}),
             'DJ Bravo': defaultdict(int,
                         {0: 419, 1: 365, 2: 93, 3: 5, 4: 102, 6: 48}),
             'DJ Harris': defaultdict(int, {0: 52, 1: 33, 2: 2, 4: 11, 6: 5}),
             'DJ Hooda': defaultdict(int,
                         {0: 92, 1: 117, 2: 28, 4: 20, 6: 20}),
             'DJ Hussey': defaultdict(int,
                         {0: 425, 1: 452, 2: 72, 3: 2, 4: 90, 6: 60}),
             'DJ Jacobs': defaultdict(int, {0: 62, 1: 22, 2: 3, 4: 10, 6: 4}),
             'DJ Muthuswami': defaultdict(int, {0: 2, 1: 1}),
             'DJ Thornely': defaultdict(int, {0: 31, 1: 19, 4: 2, 6: 2}),
             'DJG Sammy': defaultdict(int,
                         {0: 108, 1: 94, 2: 15, 3: 1, 4: 15, 6: 18}),
             'DL Chahar': defaultdict(int, {0: 2, 1: 2, 6: 2}),
             'DL Vettori': defaultdict(int,
                         {0: 46, 1: 54, 2: 4, 3: 1, 4: 11, 6: 2}),
             'DM Bravo': defaultdict(int, {0: 2, 1: 2, 4: 1}),
             'DNT Zoysa': defaultdict(int, {0: 3, 1: 3, 2: 2, 4: 1}),
             'DP Nannes': defaultdict(int, {0: 9, 1: 4}),
             'DP Vijaykumar': defaultdict(int, {1: 1}),
             'DPMD Jayawardene': defaultdict(int,
                         {0: 619, 1: 565, 2: 93, 3: 4, 4: 200, 5: 1, 6: 40}),
             'DR Martyn': defaultdict(int, {0: 10, 1: 15, 4: 1}),
             'DR Smith': defaultdict(int,
                         {0: 832, 1: 521, 2: 84, 3: 3, 4: 245, 5: 1, 6: 117}),
             'DS Kulkarni': defaultdict(int,
                         {0: 48, 1: 37, 2: 7, 3: 1, 4: 6, 6: 2}),
             'DS Lehmann': defaultdict(int, {0: 10, 1: 6, 4: 3}),
             'DT Christian': defaultdict(int,
                         {0: 119, 1: 162, 2: 28, 3: 2, 4: 22, 6: 18}),
             'DT Patil': defaultdict(int, {0: 5, 1: 5, 2: 2, 4: 1}),
             'DW Steyn': defaultdict(int, {0: 71, 1: 54, 2: 19, 4: 14, 6: 3}),
             'EJG Morgan': defaultdict(int,
                         {0: 312, 1: 255, 2: 49, 3: 3, 4: 72, 6: 34}),
             'ER Dwivedi': defaultdict(int, {0: 7, 1: 4, 4: 2, 6: 2}),
             'F Behardien': defaultdict(int, {0: 5, 1: 6, 4: 2}),
             'F du Plessis': defaultdict(int,
                         {0: 359, 1: 453, 2: 75, 3: 8, 4: 110, 6: 38}),
             'FH Edwards': defaultdict(int, {0: 3, 1: 1, 3: 1}),
             'FY Fazal': defaultdict(int, {0: 74, 1: 75, 2: 7, 4: 22, 6: 1}),
             'G Gambhir': defaultdict(int,
                         {0: 1318, 1: 1313, 2: 245, 3: 15, 4: 484, 6: 58}),
             'GB Hogg': defaultdict(int, {0: 5, 1: 14, 2: 2, 4: 1}),
             'GC Smith': defaultdict(int,
                         {0: 320, 1: 228, 2: 39, 3: 1, 4: 94, 6: 9}),
             'GD McGrath': defaultdict(int, {0: 4, 4: 1}),
             'GH Vihari': defaultdict(int,
                         {0: 142, 1: 133, 2: 23, 3: 1, 4: 23, 6: 1}),
             'GJ Bailey': defaultdict(int,
                         {0: 207, 1: 222, 2: 44, 3: 1, 4: 59, 6: 19}),
             'GJ Maxwell': defaultdict(int,
                         {0: 305, 1: 241, 2: 56, 4: 96, 6: 82}),
             'GR Napier': defaultdict(int, {0: 7, 1: 5, 2: 3, 4: 1}),
             'Gurkeerat Singh': defaultdict(int,
                         {0: 107, 1: 112, 2: 16, 4: 36, 6: 9}),
             'H Das': defaultdict(int, {0: 3, 1: 2}),
             'HH Gibbs': defaultdict(int,
                         {0: 410, 1: 264, 2: 45, 3: 3, 4: 83, 5: 1, 6: 31}),
             'HH Pandya': defaultdict(int,
                         {0: 128, 1: 113, 2: 10, 3: 3, 4: 24, 6: 28}),
             'HM Amla': defaultdict(int,
                         {0: 150, 1: 164, 2: 22, 3: 1, 4: 60, 6: 21}),
             'HV Patel': defaultdict(int, {0: 15, 1: 15, 2: 3, 4: 2, 6: 3}),
             'Harbhajan Singh': defaultdict(int,
                         {0: 258, 1: 183, 2: 33, 4: 76, 6: 41}),
             'Harmeet Singh': defaultdict(int, {0: 5, 1: 2, 2: 2, 4: 3}),
             'Harpreet Singh': defaultdict(int, {0: 8, 1: 16, 2: 2}),
             'I Malhotra': defaultdict(int, {1: 3, 4: 1}),
             'I Sharma': defaultdict(int, {0: 31, 1: 21, 2: 3, 4: 3, 6: 1}),
             'IC Pandey': defaultdict(int, {0: 2}),
             'IK Pathan': defaultdict(int,
                         {0: 373, 1: 407, 2: 76, 3: 2, 4: 88, 5: 1, 6: 38}),
             'IR Jaggi': defaultdict(int, {0: 51, 1: 36, 2: 5, 3: 2, 4: 6}),
             'Imran Tahir': defaultdict(int, {0: 17, 1: 4, 2: 1, 4: 3}),
             'Iqbal Abdulla': defaultdict(int,
                         {0: 36, 1: 34, 2: 6, 4: 9, 6: 1}),
             'Ishan Kishan': defaultdict(int,
                         {0: 113, 1: 85, 2: 10, 4: 34, 6: 13}),
             'J Arunkumar': defaultdict(int, {0: 16, 1: 3, 4: 5}),
             'J Botha': defaultdict(int,
                         {0: 138, 1: 143, 2: 37, 3: 2, 4: 39, 6: 5}),
             'J Suchith': defaultdict(int, {0: 12, 1: 10, 2: 5, 4: 4, 6: 2}),
             'J Syed Mohammad': defaultdict(int, {0: 11, 1: 11, 2: 1, 4: 4}),
             'J Theron': defaultdict(int, {0: 6, 1: 6, 4: 1}),
             'J Yadav': defaultdict(int, {0: 6, 1: 6}),
             'JA Morkel': defaultdict(int,
                         {0: 252, 1: 288, 2: 55, 3: 1, 4: 61, 6: 55}),
             'JC Buttler': defaultdict(int,
                         {0: 152, 1: 125, 2: 21, 4: 50, 5: 1, 6: 26}),
             'JD Ryder': defaultdict(int,
                         {0: 200, 1: 145, 2: 30, 3: 3, 4: 69, 6: 19}),
             'JD Unadkat': defaultdict(int, {0: 8, 1: 5}),
             'JDP Oram': defaultdict(int, {0: 50, 1: 46, 2: 3, 4: 6, 6: 5}),
             'JDS Neesham': defaultdict(int, {0: 25, 1: 10, 2: 7, 4: 3, 6: 1}),
             'JE Taylor': defaultdict(int, {0: 2, 1: 1, 2: 1}),
             'JEC Franklin': defaultdict(int,
                         {0: 124, 1: 129, 2: 22, 4: 25, 6: 9}),
             'JH Kallis': defaultdict(int,
                         {0: 982, 1: 888, 2: 113, 3: 8, 4: 255, 5: 1, 6: 44}),
             'JJ Bumrah': defaultdict(int, {0: 12, 1: 11, 2: 2, 4: 1, 6: 1}),
             'JJ Roy': defaultdict(int, {0: 16, 1: 13, 2: 2, 4: 9, 6: 1}),
             'JJ van der Wath': defaultdict(int,
                         {0: 8, 1: 6, 2: 1, 4: 1, 6: 1}),
             'JM Kemp': defaultdict(int,
                         {0: 11, 1: 9, 2: 2, 3: 1, 4: 1, 6: 1}),
             'JO Holder': defaultdict(int, {0: 18, 1: 6, 2: 2, 4: 4, 6: 2}),
             'JP Duminy': defaultdict(int,
                         {0: 535, 1: 769, 2: 123, 3: 6, 4: 123, 6: 78}),
             'JP Faulkner': defaultdict(int,
                         {0: 145, 1: 160, 2: 41, 3: 1, 4: 36, 6: 23}),
             'JR Hopes': defaultdict(int,
                         {0: 120, 1: 114, 2: 19, 3: 1, 4: 49, 6: 11}),
             'Jaskaran Singh': defaultdict(int, {0: 5, 1: 4, 2: 2}),
             'Joginder Sharma': defaultdict(int,
                         {0: 10, 1: 14, 2: 3, 4: 1, 6: 2}),
             'K Goel': defaultdict(int,
                         {0: 130, 1: 71, 2: 11, 3: 1, 4: 17, 6: 9}),
             'K Rabada': defaultdict(int, {0: 35, 1: 25, 2: 2, 4: 5, 6: 1}),
             'K Upadhyay': defaultdict(int, {0: 3, 1: 4, 2: 1, 6: 1}),
             'KA Pollard': defaultdict(int,
                         {0: 654, 1: 599, 2: 110, 3: 5, 4: 158, 6: 148}),
             'KAJ Roach': defaultdict(int, {0: 3, 1: 4, 2: 1, 4: 1}),
             'KB Arun Karthik': defaultdict(int,
                         {0: 24, 1: 20, 2: 3, 3: 1, 4: 4, 6: 1}),
             'KC Cariappa': defaultdict(int, {0: 8, 1: 9, 6: 1}),
             'KC Sangakkara': defaultdict(int,
                         {0: 552, 1: 563, 2: 81, 3: 5, 4: 195, 5: 1, 6: 27}),
             'KD Karthik': defaultdict(int,
                         {0: 862, 1: 964, 2: 168, 3: 6, 4: 286, 5: 3, 6: 71}),
             'KH Pandya': defaultdict(int,
                         {0: 108, 1: 105, 2: 31, 3: 3, 4: 46, 6: 20}),
             'KJ Abbott': defaultdict(int, {0: 3, 1: 2, 2: 1, 3: 1, 6: 1}),
             'KK Cooper': defaultdict(int, {0: 29, 1: 16, 2: 8, 4: 9, 6: 8}),
             'KK Nair': defaultdict(int,
                         {0: 384, 1: 313, 2: 66, 3: 4, 4: 135, 5: 1, 6: 26}),
             'KL Rahul': defaultdict(int,
                         {0: 217, 1: 246, 2: 41, 3: 3, 4: 61, 6: 24}),
             'KM Jadhav': defaultdict(int,
                         {0: 223, 1: 306, 2: 49, 3: 1, 4: 72, 6: 33}),
             'KMDN Kulasekara': defaultdict(int, {0: 1, 1: 1, 4: 1}),
             'KP Appanna': defaultdict(int, {0: 2, 1: 2}),
             'KP Pietersen': defaultdict(int,
                         {0: 290, 1: 284, 2: 48, 3: 4, 4: 91, 5: 1, 6: 40}),
             'KS Williamson': defaultdict(int,
                         {0: 108, 1: 141, 2: 28, 3: 1, 4: 35, 5: 1, 6: 11}),
             'KV Sharma': defaultdict(int,
                         {0: 116, 1: 114, 2: 22, 3: 1, 4: 18, 6: 14}),
             'KW Richardson': defaultdict(int,
                         {0: 17, 1: 16, 2: 3, 4: 2, 6: 1}),
             'Kamran Akmal': defaultdict(int,
                         {0: 33, 1: 20, 2: 4, 4: 13, 6: 8}),
             'Kamran Khan': defaultdict(int, {0: 3, 1: 1, 2: 1}),
             'Karanveer Singh': defaultdict(int, {0: 9, 1: 6, 2: 1, 4: 1}),
             'Kuldeep Yadav': defaultdict(int, {0: 9, 1: 10, 2: 1, 4: 2}),
             'L Ablish': defaultdict(int, {0: 2}),
             'L Balaji': defaultdict(int,
                         {0: 29, 1: 15, 2: 2, 3: 1, 4: 2, 6: 1}),
             'L Ronchi': defaultdict(int, {0: 26, 1: 4, 4: 6, 6: 1}),
             'LA Carseldine': defaultdict(int,
                         {0: 31, 1: 23, 2: 4, 3: 2, 4: 11}),
             'LA Pomersbach': defaultdict(int,
                         {0: 109, 1: 85, 2: 18, 3: 1, 4: 25, 6: 13}),
             'LH Ferguson': defaultdict(int, {1: 1}),
             'LJ Wright': defaultdict(int, {0: 22, 1: 20, 2: 2, 4: 16, 6: 3}),
             'LMP Simmons': defaultdict(int,
                         {0: 402, 1: 269, 2: 52, 3: 2, 4: 109, 6: 44}),
             'LPC Silva': defaultdict(int, {0: 10, 1: 8, 2: 3, 4: 5, 6: 1}),
             'LR Shukla': defaultdict(int,
                         {0: 152, 1: 137, 2: 20, 4: 33, 6: 16}),
             'LRPL Taylor': defaultdict(int,
                         {0: 334, 1: 334, 2: 62, 3: 3, 4: 66, 5: 2, 6: 46}),
             'M Ashwin': defaultdict(int, {0: 1}),

In [8]:
with open("batsmanruns.csv","w") as f:
    f.write("{},{},{},{},{},{},{},{}\n".format("player","runs","0","1","2","3","4","6"))
    for x,y in sorted(player.items(), key=lambda x:x[1],reverse=True):
        runs = player_runs[x]
        f.write("{},{},{}\n".format(x,y,runs))

In [5]:
sorted(player.items(), key=lambda x:x[1],reverse=True)

[('SK Raina', 4548),
 ('V Kohli', 4423),
 ('RG Sharma', 4207),
 ('G Gambhir', 4132),
 ('DA Warner', 4014),
 ('RV Uthappa', 3778),
 ('CH Gayle', 3651),
 ('S Dhawan', 3561),
 ('MS Dhoni', 3560),
 ('AB de Villiers', 3486),
 ('AM Rahane', 3057),
 ('YK Pathan', 2922),
 ('KD Karthik', 2903),
 ('BB McCullum', 2755),
 ('V Sehwag', 2728),
 ('SR Watson', 2628),
 ('Yuvraj Singh', 2591),
 ('M Vijay', 2511),
 ('SE Marsh', 2489),
 ('JH Kallis', 2427),
 ('AT Rayudu', 2416),
 ('DR Smith', 2385),
 ('KA Pollard', 2354),
 ('SR Tendulkar', 2334),
 ('PA Patel', 2322),
 ('MK Pandey', 2223),
 ('R Dravid', 2174),
 ('AC Gilchrist', 2069),
 ('JP Duminy', 1993),
 ('MEK Hussey', 1977),
 ('DPMD Jayawardene', 1808),
 ('RA Jadeja', 1732),
 ('SPD Smith', 1713),
 ('KC Sangakkara', 1687),
 ('MK Tiwary', 1648),
 ('AJ Finch', 1604),
 ('DA Miller', 1563),
 ('WP Saha', 1557),
 ('NV Ojha', 1553),
 ('S Badrinath', 1441),
 ('SV Samson', 1426),
 ('BJ Hodge', 1400),
 ('SC Ganguly', 1349),
 ('DJ Hussey', 1322),
 ('F du Plessis', 1295),
 ('SS Tiwary', 1276),
 ('DJ Bravo', 1262),
 ('GJ Maxwell', 1229),
 ('KK Nair', 1158),
 ('TM Dilshan', 1153),
 ('IK Pathan', 1150),
 ('Mandeep Singh', 1112),
 ('ML Hayden', 1107),
 ('LMP Simmons', 1079),
 ('LRPL Taylor', 1017),
 ('KP Pietersen', 1001),
 ('Y Venugopal Rao', 985),
 ('JA Morkel', 975),
 ('A Symonds', 974),
 ('CL White', 971),
 ('MC Henriques', 969),
 ('M Vohra', 957),
 ('KM Jadhav', 893),
 ('HH Gibbs', 886),
 ('EJG Morgan', 854),
 ('MA Agarwal', 814),
 ('SS Iyer', 807),
 ('Harbhajan Singh', 799),
 ('MS Bisla', 798),
 ('ST Jayasuriya', 768),
 ('STR Binny', 766),
 ('GC Smith', 739),
 ('Q de Kock', 726),
 ('KL Rahul', 725),
 ('AD Mathews', 724),
 ('TL Suman', 676),
 ('AM Nayar', 672),
 ('GJ Bailey', 663),
 ('SA Yadav', 608),
 ('AR Patel', 606),
 ('JD Ryder', 604),
 ('HM Amla', 577),
 ('AD Russell', 574),
 ('RR Pant', 564),
 ('RS Bopara', 531),
 ('JC Buttler', 528),
 ('JP Faulkner', 527),
 ('CJ Anderson', 521),
 ('PP Chawla', 515),
 ('M Manhas', 514),
 ('OA Shah', 506),
 ('PC Valthaty', 505),
 ('Shakib Al Hasan', 500),
 ('KH Pandya', 480),
 ('CH Morris', 439),
 ('N Rana', 437),
 ('NLTC Perera', 424),
 ('SA Asnodkar', 423),
 ('DT Christian', 420),
 ('JR Hopes', 417),
 ('KS Williamson', 411),
 ('J Botha', 409),
 ('HH Pandya', 406),
 ('LR Shukla', 405),
 ('AL Menaria', 401),
 ('MV Boucher', 394),
 ('RA Tripathi', 391),
 ('CA Pujara', 390),
 ('Azhar Mahmood', 388),
 ('CA Lynn', 384),
 ('DB Ravi Teja', 375),
 ('DJ Hooda', 373),
 ('S Sohal', 368),
 ('P Negi', 353),
 ('R Bhatia', 342),
 ('Gurkeerat Singh', 342),
 ('A Mishra', 340),
 ('P Kumar', 340),
 ('AP Tare', 339),
 ('JEC Franklin', 327),
 ('RN ten Doeschate', 326),
 ('Ishan Kishan', 319),
 ('KV Sharma', 317),
 ('BA Stokes', 316),
 ('R Vinay Kumar', 304),
 ('DB Das', 304),
 ('LA Pomersbach', 302),
 ('UBT Chand', 300),
 ('DJG Sammy', 295),
 ('Y Nagar', 285),
 ('VVS Laxman', 282),
 ('B Chipli', 280),
 ('A Ashish Reddy', 280),
 ('GH Vihari', 280),
 ('MJ Lumb', 278),
 ('SP Narine', 271),
 ('R Sathish', 270),
 ('M Kaif', 259),
 ('SM Katich', 241),
 ('SP Goswami', 241),
 ('MD Mishra', 237),
 ('R Ashwin', 231),
 ('SW Billings', 226),
 ('MR Marsh', 225),
 ('K Goel', 218),
 ('AA Jhunjhunwala', 217),
 ('TM Head', 205),
 ('PD Collingwood', 203),
 ('SK Warne', 198),
 ('SP Fleming', 196),
 ('AS Raut', 194),
 ('Salman Butt', 193),
 ('BJ Rohrer', 193),
 ('YV Takawale', 192),
 ('MJ Guptill', 189),
 ('Bipul Sharma', 187),
 ('FY Fazal', 183),
 ('AC Voges', 181),
 ('AB Agarkar', 179),
 ('MF Maharoof', 177),
 ('SN Khan', 177),
 ('DH Yagnik', 170),
 ('CM Gautam', 169),
 ('MN van Wyk', 167),
 ('DW Steyn', 166),
 ('PA Reddy', 164),
 ('MP Stoinis', 163),
 ('MN Samuels', 161),
 ('RE van der Merwe', 159),
 ('R McLaren', 159),
 ('B Kumar', 158),
 ('R Dhawan', 153),
 ('MG Johnson', 151),
 ('SM Pollock', 147),
 ('S Vidyut', 145),
 ('N Saini', 140),
 ('Sachin Baby', 137),
 ('S Anirudha', 136),
 ('SB Styris', 131),
 ('W Jaffer', 130),
 ('Kamran Akmal', 128),
 ('P Dogra', 127),
 ('D Wiese', 127),
 ('UT Khawaja', 127),
 ('C de Grandhomme', 126),
 ('M Morkel', 126),
 ('BB Samantray', 125),
 ('MC Juneja', 125),
 ('BCJ Cutting', 124),
 ('B Lee', 124),
 ('AB McDonald', 123),
 ('Niraj Patel', 121),
 ('DL Vettori', 121),
 ('AC Blizzard', 120),
 ('Z Khan', 117),
 ('Misbah-ul-Haq', 117),
 ('RJ Harris', 117),
 ('KK Cooper', 116),
 ('M Kartik', 113),
 ('MM Sharma', 112),
 ('DJ Harris', 111),
 ('JDP Oram', 106),
 ('LJ Wright', 106),
 ('RJ Quiney', 103),
 ('V Shankar', 101),
 ('MS Gony', 99),
 ('SD Chitnis', 99),
 ('CJ Ferguson', 98),
 ('MJ Clarke', 98),
 ('MA Starc', 96),
 ('CR Brathwaite', 95),
 ('UT Yadav', 94),
 ('PR Shah', 92),
 ('DJ Jacobs', 92),
 ('RT Ponting', 91),
 ('S Rana', 91),
 ('DS Kulkarni', 90),
 ('Iqbal Abdulla', 88),
 ('SL Malinga', 88),
 ('Ankit Sharma', 87),
 ('AP Majumdar', 87),
 ('RE Levi', 83),
 ('WPUJC Vaas', 81),
 ('Shahid Afridi', 81),
 ('LA Carseldine', 81),
 ('AD Mascarenhas', 79),
 ('PJ Cummins', 77),
 ('IR Jaggi', 76),
 ('B Akhil', 76),
 ('TR Birt', 75),
 ('RR Sarwan', 73),
 ('M Klinger', 73),
 ('AA Bilakhia', 69),
 ('RR Powar', 67),
 ('R Sharma', 66),
 ('Mohammad Hafeez', 64),
 ('MJ McClenaghan', 63),
 ('Anirudh Singh', 63),
 ('WD Parnell', 63),
 ('A Flintoff', 62),
 ('S Aravind', 59),
 ('JJ Roy', 59),
 ('WA Mota', 56),
 ('K Rabada', 55),
 ('M Rawat', 55),
 ('TG Southee', 54),
 ('AJ Tye', 53),
 ('A Chopra', 53),
 ('RR Rossouw', 53),
 ('NM Coulter-Nile', 52),
 ('RP Singh', 52),
 ('Shoaib Malik', 52),
 ('KB Arun Karthik', 51),
 ('R Rampaul', 51),
 ('RV Gomez', 50),
 ('AS Yadav', 49),
 ('SB Bangar', 49),
 ('AG Paunikar', 49),
 ('J Suchith', 48),
 ('Yashpal Singh', 47),
 ('HV Patel', 47),
 ('CR Woakes', 46),
 ('VR Aaron', 46),
 ('Mohammed Shami', 46),
 ('I Sharma', 45),
 ('Sunny Singh', 43),
 ('SK Trivedi', 42),
 ('AB Barath', 42),
 ('JDS Neesham', 42),
 ('A Nehra', 41),
 ('LPC Silva', 40),
 ('BR Dunk', 40),
 ('MM Patel', 39),
 ('DJ Thornely', 39),
 ('Umar Gul', 39),
 ('AUK Pathan', 39),
 ('SP Jackson', 38),
 ('JO Holder', 38),
 ('S Narwal', 37),
 ('Sohail Tanvir', 36),
 ('Joginder Sharma', 36),
 ('L Balaji', 36),
 ('AN Ahmed', 36),
 ('KW Richardson', 36),
 ('R Tewatia', 35),
 ('A Kumble', 35),
 ('B Sumanth', 35),
 ('L Ronchi', 34),
 ('S Sreesanth', 34),
 ('A Mithun', 34),
 ('AP Dole', 34),
 ('Anureet Singh', 33),
 ('D Salunkhe', 33),
 ('RJ Peterson', 32),
 ('T Taibu', 31),
 ('S Sriram', 31),
 ('C Munro', 30),
 ('J Syed Mohammad', 29),
 ('VH Zol', 29),
 ('Basil Thampi', 28),
 ('SB Jakati', 28),
 ('S Nadeem', 26),
 ('AB Dinda', 26),
 ('Sandeep Sharma', 26),
 ('JM Kemp', 26),
 ('NL McCullum', 26),
 ('A Choudhary', 25),
 ('JJ Bumrah', 25),
 ('S Chanderpaul', 25),
 ('PJ Sangwan', 24),
 ('MA Khote', 24),
 ('ER Dwivedi', 24),
 ('J Arunkumar', 23),
 ('SW Tait', 23),
 ('BMAJ Mendis', 23),
 ('NS Naik', 23),
 ('MS Wade', 22),
 ('GB Hogg', 22),
 ('DE Bollinger', 21),
 ('CA Ingram', 21),
 ('AD Nath', 20),
 ('Kuldeep Yadav', 20),
 ('RR Raje', 20),
 ('M Muralitharan', 20),
 ('AC Thomas', 20),
 ('Harpreet Singh', 20),
 ('NJ Maddinson', 20),
 ('Vishnu Vinod', 19),
 ('A Mukund', 19),
 ('R Bishnoi', 19),
 ('DR Martyn', 19),
 ('Y Gnaneswara Rao', 19),
 ('R Shukla', 19),
 ('P Sahu', 19),
 ('Imran Tahir', 18),
 ('DS Lehmann', 18),
 ('Harmeet Singh', 18),
 ('JJ van der Wath', 18),
 ('BJ Haddin', 18),
 ('PV Tambe', 18),
 ('Parvez Rasool', 17),
 ('CK Kapugedera', 16),
 ('PP Ojha', 16),
 ('YS Chahal', 15),
 ('KC Cariappa', 15),
 ('VY Mahesh', 15),
 ('GR Napier', 15),
 ('C Madan', 15),
 ('SA Abbott', 15),
 ('DL Chahar', 14),
 ('MDKJ Perera', 14),
 ('S Gopal', 14),
 ('F Behardien', 14),
 ('S Badree', 13),
 ('DT Patil', 13),
 ('KJ Abbott', 13),
 ('AR Bawne', 12),
 ('Swapnil Singh', 12),
 ('T Thushara', 12),
 ('AA Chavan', 12),
 ('DAJ Bracewell', 12),
 ('K Upadhyay', 12),
 ('Karanveer Singh', 12),
 ('Rashid Khan', 11),
 ('T Kohli', 11),
 ('DNT Zoysa', 11),
 ('M Ntini', 11),
 ('T Henderson', 11),
 ('D du Preez', 10),
 ('J Theron', 10),
 ('KAJ Roach', 10),
 ('TD Paine', 10),
 ('AG Murtaza', 10),
 ('SMSM Senanayake', 10),
 ('X Thalaivan Sargunam', 10),
 ('Washington Sundar', 9),
 ('S Kaul', 9),
 ('AA Noffke', 9),
 ('SM Harwood', 9),
 ('TS Mills', 8),
 ('TM Srivastava', 8),
 ('Jaskaran Singh', 8),
 ('CK Langeveldt', 8),
 ('CJ McKay', 8),
 ('SN Thakur', 7),
 ('AF Milne', 7),
 ('Ankit Soni', 7),
 ('Pankaj Singh', 7),
 ('AN Ghosh', 7),
 ('VS Malik', 7),
 ('I Malhotra', 7),
 ('UA Birla', 7),
 ('DM Bravo', 6),
 ('AS Rajpoot', 6),
 ('SB Joshi', 6),
 ('SS Shaikh', 6),
 ('BA Bhatt', 6),
 ('PSP Handscomb', 6),
 ('J Yadav', 6),
 ('A Zampa', 5),
 ('JD Unadkat', 5),
 ('TA Boult', 5),
 ('SJ Srivastava', 5),
 ('KMDN Kulasekara', 5),
 ('P Awana', 5),
 ('Shivam Sharma', 5),
 ('VRV Singh', 4),
 ('GD McGrath', 4),
 ('CRD Fernando', 4),
 ('FH Edwards', 4),
 ('A Uniyal', 4),
 ('DP Nannes', 4),
 ('RS Sodhi', 4),
 ('A Chandila', 4),
 ('B Laughlin', 4),
 ('BB Sran', 4),
 ('RD Chahar', 3),
 ('CJ Jordan', 3),
 ('D Kalyankrishna', 3),
 ('Mohammad Asif', 3),
 ('Younis Khan', 3),
 ('Kamran Khan', 3),
 ('BAW Mendis', 3),
 ('S Tyagi', 3),
 ('R Ninan', 3),
 ('JE Taylor', 3),
 ('Mohammad Nabi', 2),
 ('Shoaib Akhtar', 2),
 ('H Das', 2),
 ('VS Yeligati', 2),
 ('KP Appanna', 2),
 ('Mashrafe Mortaza', 2),
 ('A Singh', 2),
 ('Mohammad Ashraful', 2),
 ('RS Gavaskar', 2),
 ('SB Wagh', 2),
 ('S Randiv', 2),
 ('RG More', 2),
 ('LH Ferguson', 1),
 ('PM Sarvesh Kumar', 1),
 ('DP Vijaykumar', 1),
 ('Shoaib Ahmed', 1),
 ('SE Bond', 1),
 ('NJ Rimmington', 1),
 ('P Parameswaran', 1),
 ('BE Hendricks', 1),
 ('M de Lange', 1),
 ('DJ Muthuswami', 1),
 ('U Kaul', 0),
 ('Abdur Razzak', 0),
 ('C Nanda', 0),
 ('YA Abdulla', 0),
 ('S Ladda', 0),
 ('L Ablish', 0),
 ('ND Doshi', 0),
 ('RR Bhatkal', 0),
 ('V Pratap Singh', 0),
 ('Sunny Gupta', 0),
 ('IC Pandey', 0),
 ('M Ashwin', 0),
 ('S Kaushik', 0)]

In [9]:
test = pd.read_csv("batsmanruns.csv")

In [10]:
test.head(100)

,player,runsSK Raina,4548,defaultdict(<class 'int'>,{0: 1163,1: 1377,4: 402,2: 242,6: 174,3: 10,5: 1})
0,V Kohli,4423,defaultdict(<class 'int'>,{0: 1287,1: 1410,6: 160,2: 242,4: 384,3: 11}),NaN,NaN
1,RG Sharma,4207,defaultdict(<class 'int'>,{0: 1185,1: 1379,3: 5,2: 177,4: 354,6: 173,5: 1}),NaN
2,G Gambhir,4132,defaultdict(<class 'int'>,{1: 1313,0: 1318,4: 484,2: 245,6: 58,3: 15}),NaN,NaN
3,DA Warner,4014,defaultdict(<class 'int'>,{0: 1124,4: 401,6: 160,1: 997,2: 207,3: 13}),NaN,NaN
4,RV Uthappa,3778,defaultdict(<class 'int'>,{0: 1165,4: 377,6: 125,2: 191,1: 1087,3: 12,5: 3}),NaN
5,CH Gayle,3651,defaultdict(<class 'int'>,{1: 718,0: 1178,4: 297,6: 266,2: 70,3: 3}),NaN,NaN
6,S Dhawan,3561,defaultdict(<class 'int'>,{0: 1210,1: 1137,4: 401,2: 168,6: 71,3: 16,5: 2}),NaN
7,MS Dhoni,3560,defaultdict(<class 'int'>,{1: 1085,0: 926,4: 251,6: 156,2: 251,3: 11}),NaN,NaN
8,AB de Villiers,3486,defaultdict(<class 'int'>,{4: 287,0: 778,6: 158,1: 980,2: 187,3: 12}),NaN,NaN
9,AM Rahane,3057,defaultdict(<class 'int'>,{1: 1039,0: 1001,4: 320,6: 60,2: 168,3: 14}),NaN,NaN
10,YK Pathan,2922,defaultdict(<class 'int'>,{0: 765,2: 136,1: 781,4: 240,6: 149,3: 5}),NaN,NaN
11,KD Karthik,2903,defaultdict(<class 'int'>,{0: 862,1: 964,4: 286,6: 71,2: 168,5: 3,3: 6}),NaN
12,BB McCullum,2755,defaultdict(<class 'int'>,{1: 690,0: 985,4: 277,6: 124,2: 102,3: 3}),NaN,NaN
13,V Sehwag,2728,defaultdict(<class 'int'>,{4: 334,0: 737,1: 558,2: 96,6: 106,3: 2}),NaN,NaN
14,SR Watson,2628,defaultdict(<class 'int'>,{1: 638,2: 101,0: 822,6: 122,4: 258,3: 8}),NaN,NaN
15,Yuvraj Singh,2591,defaultdict(<class 'int'>,{2: 113,0: 898,1: 690,4: 205,6: 141,3: 3}),NaN,NaN
16,M Vijay,2511,defaultdict(<class 'int'>,{0: 930,1: 663,4: 237,2: 155,6: 89,5: 1,3: 17}),NaN
17,SE Marsh,2489,defaultdict(<class 'int'>,{0: 736,4: 269,1: 724,6: 78,2: 99,3: 6,5: 1}),NaN
18,JH Kallis,2427,defaultdict(<class 'int'>,{1: 888,0: 982,6: 44,4: 255,2: 113,3: 8,5: 1}),NaN
19,AT Rayudu,2416,defaultdict(<class 'int'>,{1: 853,0: 693,2: 133,4: 205,6: 79,3: 1}),NaN,NaN
20,DR Smith,2385,defaultdict(<class 'int'>,{1: 521,0: 832,4: 245,2: 84,6: 117,3: 3,5: 1}),NaN
21,KA Pollard,2354,defaultdict(<class 'int'>,{1: 599,4: 158,0: 654,6: 148,2: 110,3: 5}),NaN,NaN
22,SR Tendulkar,2334,defaultdict(<class 'int'>,{1: 721,0: 874,4: 296,2: 117,6: 29,3: 7}),NaN,NaN
23,PA Patel,2322,defaultdict(<class 'int'>,{0: 933,1: 677,4: 297,2: 109,6: 35,3: 8,5: 1}),NaN
24,MK Pandey,2223,defaultdict(<class 'int'>,{0: 737,1: 772,2: 121,4: 197,6: 65,3: 7,5: 2}),NaN
25,R Dravid,2174,defaultdict(<class 'int'>,{1: 681,0: 819,4: 269,2: 118,6: 28,5: 2,3: 1}),NaN
26,AC Gilchrist,2069,defaultdict(<class 'int'>,{1: 417,0: 737,6: 92,4: 239,2: 66,3: 4}),NaN,NaN
27,JP Duminy,1993,defaultdict(<class 'int'>,{1: 769,4: 123,0: 535,6: 78,2: 123,3: 6}),NaN,NaN
28,MEK Hussey,1977,defaultdict(<class 'int'>,{1: 648,0: 643,4: 198,2: 96,6: 52,3: 11}),NaN,NaN
29,DPMD Jayawardene,1808,defaultdict(<class 'int'>,{0: 619,1: 565,6: 40,2: 93,4: 200,3: 4,5: 1}),NaN
...,...,...,...,...,...,...,...,...,...,...,...
70,GC Smith,739,defaultdict(<class 'int'>,{0: 320,4: 94,1: 228,6: 9,2: 39,3: 1}),NaN,NaN
71,Q de Kock,726,defaultdict(<class 'int'>,{0: 244,1: 188,4: 90,6: 21,2: 19,3: 3,5: 1}),NaN
72,KL Rahul,725,defaultdict(<class 'int'>,{0: 217,1: 246,4: 61,2: 41,6: 24,3: 3}),NaN,NaN
73,AD Mathews,724,defaultdict(<class 'int'>,{1: 267,0: 207,4: 44,2: 49,6: 29,3: 3}),NaN,NaN
74,TL Suman,676,defaultdict(<class 'int'>,{1: 205,0: 255,4: 55,6: 26,3: 3,2: 43}),NaN,NaN
75,AM Nayar,672,defaultdict(<class 'int'>,{0: 234,1: 230,4: 55,2: 47,6: 20,5: 1,3: 1}),NaN
76,GJ Bailey,663,defaultdict(<class 'int'>,{0: 207,4: 59,1: 222,2: 44,6: 19,3: 1}),NaN,NaN
77,SA Yadav,608,defaultdict(<class 'int'>,{1: 196,0: 174,4: 54,2: 32,6: 21,3: 2}),NaN,NaN
78,AR Patel,606,defaultdict(<class 'int'>,{1: 224,4: 34,0: 169,2: 39,6: 28}),NaN,NaN,NaN
79,JD Ryder,604,defaultdict(<class 'int'>,{0: 200,4: 69,2: 30,1: 145,3: 3,6: 19}),NaN,NaN
80,HM Amla,577,defaultdict(<class 'int'>,{0: 150,4: 60,1: 164,6: 21,2: 22,3: 1}),NaN,NaN
81,AD Russell,574,defaultdict(<class 'int'>,{6: 37,1: 114,4: 48,0: 128,2: 23}),NaN,NaN,NaN
82,RR Pant,564,defaultdict(<class 'int'>,{6: 30,0: 134,1: 145,2: 24,4: 47,3: 1}),NaN,NaN
83,RS Bopara,531,defaultdict(<class 'int'>,{0: 175,2: 27,1: 204,6: 16,4: 39,3: 7}),NaN,NaN
84,JC Buttler,528,defaultdict(<class 'int'>,{5: 1,4: 50,0: 152,6: 26,1: 125,2: 21}),NaN,NaN
85,JP Faulkner,527,defaultdict(<class 'int'>,{3: 1,1: 160,0: 145,4: 36,2: 41,6: 23}),NaN,NaN
86,CJ Anderson,521,defaultdict(<class 'int'>,{0: 190,1: 128,4: 40,2: 25,6: 30,3: 1}),NaN,NaN
87,PP Chawla,515,defaultdict(<class 'int'>,{1: 163,0: 207,2: 33,4: 49,6: 15}),NaN,NaN,NaN
88,M Manhas,514,defaultdict(<class 'int'>,{0: 197,1: 191,2: 44,4: 43,6: 10,3: 1}),NaN,NaN
89,OA Shah,506,defaultdict(<class 'int'>,{0: 149,1: 168,2: 29,6: 23,4: 34,3: 2}),NaN,NaN
90,PC Valthaty,505,defaultdict(<class 'int'>,{1: 101,0: 230,4: 61,2: 20,6: 20}),NaN,NaN,NaN
91,Shakib Al Hasan,500,defaultdict(<class 'int'>,{1: 170,0: 140,4: 44,2: 32,6: 15}),NaN,NaN,NaN
92,KH Pandya,480,defaultdict(<class 'int'>,{1: 105,0: 108,4: 46,3: 3,2: 31,6: 20}),NaN,NaN
93,CH Morris,439,defaultdict(<class 'int'>,{1: 113,0: 78,4: 33,2: 28,6: 23}),NaN,NaN,NaN
94,N Rana,437,defaultdict(<class 'int'>,{1: 134,0: 151,6: 25,2: 13,4: 31,3: 1}),NaN,NaN
95,NLTC Perera,424,defaultdict(<class 'int'>,{0: 129,1: 121,4: 23,2: 26,6: 26,3: 1}),NaN,NaN
96,SA Asnodkar,423,defaultdict(<class 'int'>,{4: 56,0: 164,1: 105,6: 10,2: 17}),NaN,NaN,NaN
97,DT Christian,420,defaultdict(<class 'int'>,{0: 119,1: 162,4: 22,6: 18,2: 28,3: 2}),NaN,NaN
98,JR Hopes,417,defaultdict(<class 'int'>,{0: 120,4: 49,1: 114,6: 11,2: 19,3: 1}),NaN,NaN
99,KS Williamson,411,defaultdict(<class 'int'>,{2: 28,0: 108,1: 141,4: 35,6: 11,5: 1,3: 1}),NaN